development: &db
  adapter: postgresql
  host: localhost
  database: filter_dev

test:
  <<: *db
  database: filter_test

production:
  host: 127.17.0.12
  user: root
  password: YgEVzH8pfpCpfdGy
  database: db
  port: 49153
