generate_podcasts:
  every: 1h
  class: GeneratePodcastsJob
  args:
  description: Generate Podcast XML File

download_episodes:
  every: 5m
  class: DownloadEpisodesJob
  args:
  description: Download episodes to S3

auto_update:
  every: 1h
  class: AutoUpdateJob
  args:
  description: Update podcasts for pro users

librato_measurements:
  every: 6h
  class: LibratoMeasurementsJob
  args:
  description: Send measurements to Librato
